# Generated by Django 5.2.6 on 2025-10-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="payment_method",
            field=models.CharField(
                choices=[("razorpay", "Razorpay"), ("cod", "Cash on Delivery")],
                max_length=20,
            ),
        ),
    ]
